#-------------------------------
# General Site Settings
title: Go For Goldman
logo: gfg.png # You can add own logo.
description: Matt Goldman's blog about tech and life


#-------------------------------
# Author Settings
author:
  name: Matt Goldman
  image: mattg.png
  say-hello: Hello, I’m <strong>Matt Goldman</strong>
  bio: Senior Software Architect at SSW. I love innovation and write about it here. 


#-------------------------------
# Contact links
twitter: https://twitter.com/mattgoldman # Add your Twitter handle
linkedin: https://www.linkedin.com/in/matt-goldman/
github: https://github.com/matt-goldman/
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: goforgoldman # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
